### PR TITLE
[Bug][Android] Language is not switched in preview when the implementation of StringsBindings is used

### LINKED ISSUE #509: [Bug][Android] Language is not switched in preview when the implementation of StringsBindings is used
**Describe the bug**
As the subject says, language is not switched in preview when the implementation of StringsBindings is used.
Found it from: https://github.com/DroidKaigi/conference-app-2023/pull/481#issuecomment-1677666124

**To Reproduce**
1. Implement StringsBindings
2. Use the above implementation in your composable
3. Create previews for the composable
4. Add locale settings to the `@Preview` parameter

**Expected behavior**
Japanese and English can be switched properly in preview

**Screenshots**
N/A

### PR DESCRIPTION
**Pull request by mikanIchinose**
## Issue
- close #509 

## Overview (Required)
- `java.util.Locale.getDefault().language` -> `androidx.compose.ui.text.intl.Locale.current.language`

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

File: core/designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2023/designsystem/strings/Lang.kt [hunk 1]
```diff
@@ -1,7 +1,7 @@
 package io.github.droidkaigi.confsched2023.designsystem.strings
 
-import java.util.Locale
+import androidx.compose.ui.text.intl.Locale
 
 actual fun lang(): String {
-    return Locale.getDefault().language
+    return Locale.current.language
```
Comment (tkhs0604) [inline core/designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2023/designsystem/strings/Lang.kt:6]: ❤

**Review by tkhs0604 — APPROVED** [review]
Looks perfect! Thank you so much! 🚀
