### PR TITLE
Adjust Timetable App Bar Bookmark Icon State

### LINKED ISSUE #1116: [Android] Unpredictable Timetable App Bar Bookmark Icon State
**Describe the bug**
Reproduced with an app released from the Play Store.
The state of the bookmark icon in the top app bar resets upon restarting the app. I'm not sure if this is the intended behavior or a bug.

**To Reproduce**
Follow these steps to reproduce the behavior:

1. Verify the visibility of the bookmark list icon in the top app bar.
2. Tap the 'bookmark icon' found on the timetable within a session item.
3. Observe that the bookmark list icon in the top app bar changes (it fills with color and a '+' appears on the icon).
4. Restart the app.
5. Notice that the bookmark list icon in the top app bar reverts to its state from step 2.

Sometimes didn't happen, but you can see the other pattern's state management problems.

**Expected behavior**
In this scenario, the state of the bookmark list icon in the top app bar should not change when the app is restarted.

**Screenshots**

I will attach the recorded one later. 🙏

### PR DESCRIPTION
**Pull request by ked4ma**
## Issue
- close #1116

## Overview (Required)
- bookmark icon has unexpected behaviors at app bar on timetable screen (refer `before` movie)
- HOT to REPRODUCTION
  1. add bookmark on timetable list screen
  2. go to bookmark screen
  3. go back to timetable list screen
- WHY the behavior like this
  - ■ when simply adding bookmark
    <details>
      <summary>expand for detail...</summary>

      | onBookmarkClickState | isPlaying | progress | remarks |
      | :--: | :--: | :--: | :--: |
      NULL | FALSE |   | [[at first]]
      TRUE | FALSE |   | when click bookmark icon
      TRUE | TRUE | 0 | start animation
      TRUE | TRUE | ~1.0 |  
      TRUE | FALSE | 1 | call onReachAnimationEnd()
      FALSE | FALSE | 1 |  
      FALSE | TRUE | 1 | isPlay will be TRUE because onBookmarkClickState is updated
      FALSE | FALSE | 0 |  
      TRUE | FALSE | 0 | [[second click]]
      TRUE | TRUE | 0 | start animation
      TRUE | TRUE | ~1.0 |  
      TRUE | FALSE | 1 | call onReachAnimationEnd()
      FALSE | FALSE | 1 |  
      FALSE | TRUE | 1 | isPlay will be TRUE because onBookmarkClickState is updated
      FALSE | FALSE | 0 |  
    </details>

  - ■ when go back from bookmark list (before going to bookmark list, adding bookmark)
    - ※1,2): operated in one composable execution
    - the problem here is 
      - **onBookmarkClickState is false at first**
      - **onBookmarkClickState is false right after click bookmark**
    <details>
      <summary>expand for detail...</summary>

      onBookmarkClickState | isPlaying | progress | remarks
      -- | -- | -- | --
      FALSE | TRUE | 0 | animation is started because onBookmarkClickState is NOT null
      FALSE | TRUE | ~1.0 |  
      FALSE | FALSE | 1 | onReachAnimationEnd()
      **isPlaying will not be TRUE again because onBookmarkClickState is FALSE at first**
      TRUE | FALSE | 1 | [[second click]]
      TRUE※1 | TRUE※1 | 1 | isPlaying become TRUE (∵onBookmarkClickState is TRUE)
      FALSE※2 | FALSE※2 | 1 | onBookmarkClickState will be updated to FALSE becuase progress is 1.0
      FALSE | TRUE | 0 | start animation becuase onBookmarkState is updated
      FALSE | TRUE | ~1.0 |  
      FALSE | FALSE | 1 | onReachAnimationEnd()
      **isPlaying will not be TRUE again because onBookmarkClickState is FALSE (unchanged)** | | | |
    </details>
- I fix this issue by changing how to judge "animation is finished"
  - use LottieAnimationState (isPlaying, isAtEnd, progress) instead of using only `progress`
  - as a result, first null value of onBookmarkClickState and animationRange could remove
  - by this, variables arround animation are changed as following
    - ■ when simply adding bookmark
      <details>
        <summary>expand for detail...</summary>

        onBookmarkClickState | isPlaying | progress(state) | isPlaying(state) | isAtEnd(state) | remarks
        -- | -- | -- | -- | -- | --
        FALSE | FALSE | 0 | FALSE | TRUE | [[at first]]
        TRUE | FALSE | 0 | FALSE | TRUE | when click bookmark icon
        TRUE | TRUE | 0 | TRUE | FALSE | start animation
        TRUE | TRUE | ~1.0 | TRUE | FALSE |  
        TRUE | TRUE | 1 | TRUE | TRUE | when animation finished
        FALSE | FALSE | 1 | FALSE | TRUE | animation state is updated according to isPlaying
        TRUE | FALSE | 1 | FALSE | TRUE | [[second click]]
        TRUE | TRUE | 0 | TRUE | FALSE | start animation
        TRUE | TRUE | ~1.0 | TRUE | FALSE |  
        TRUE | TRUE | 1 | TRUE | TRUE | when animation finished
        FALSE | FALSE | 1 | FALSE | TRUE | animation state is updated according to isPlaying
      </details>
    - ■ when go back from bookmark list (before going to bookmark list, adding bookmark)
      <details>
        <summary>expand for detail...</summary>

        onBookmarkClickState | isPlaying | progress(state) | isPlaying(state) | isAtEnd(state) | remarks
        -- | -- | -- | -- | -- | --
        FALSE | FALSE | 0 | FALSE | TRUE | animation won't start because isPlaying will be TRUE only when onBookmarkClickState is TRUE
      </details>
## Links
- nothing

## Movie
Before | After
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/da71fc7c-51c1-4c00-8de2-cca035230f96" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/74723074/030bf26b-0638-41a3-bb19-26f02ce7073e" width="300" >

### CODE REVIEW

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt [hunk 1]
```diff
@@ -25,27 +25,26 @@ import io.github.droidkaigi.confsched2023.feature.sessions.R.raw
...
-    val progress by animateLottieCompositionAsState(
+    val state = animateLottieCompositionAsState(
         composition = lottieComposition,
         isPlaying = isPlaying,
         restartOnPlay = true,
     )
 
     LaunchedEffect(onBookmarkClickStatus) {
-        if (onBookmarkClickStatus != null) {
+        if (onBookmarkClickStatus) {
```
Comment (ked4ma) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt:42]: update `isPlaying` to true only when `onBookmarkClickStatus` is `true`.
this is for not launcing animation when `onBookmarkClickState` is `false`.

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt [hunk 2]
```diff
@@ -25,27 +25,26 @@ import io.github.droidkaigi.confsched2023.feature.sessions.R.raw
...
             isPlaying = true
         }
     }
 
-    if (progress == 1f) {
+    if (state.isPlaying && state.isAtEnd) {
```
Comment (ked4ma) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt:47]: instead of judge animation ending by `progress`,
use `isPlaying` nad `isAtEnd` parameter of `LottieAnimationState`.

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt [hunk 3]
```diff
@@ -54,10 +53,10 @@ fun BookmarkIcon(
         modifier = modifier,
         contentAlignment = Alignment.Center,
     ) {
-        if (progress in animationRange) {
+        if (state.isPlaying && !state.isAtEnd) {
```
Comment (ked4ma) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt:56]: same as [L47](https://github.com/DroidKaigi/conference-app-2023/pull/1131/files#diff-5ab60002983aa4756e673f60b4537efd96e32a3ef541d84dd60778115ba16c28R47), we can judge whether animation is playing or not by `LottieAnimationState`

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/TimetableScreen.kt [hunk 4]
```diff
@@ -257,7 +257,7 @@ fun PreviewTimetableScreenDark() {
                     ),
                 ),
                 TimetableUiType.Grid,
-                null,
+                false,
```
Comment (takahirom) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/TimetableScreen.kt:260]: This is an existing implementation, but it is difficult to review because I can only see a change from null to false. Could you add a named parameter for this? 🙇

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt [hunk 5]
```diff
@@ -25,27 +25,26 @@ import io.github.droidkaigi.confsched2023.feature.sessions.R.raw
...
+    onBookmarkClickStatus: Boolean,
     onReachAnimationEnd: () -> Unit,
     modifier: Modifier = Modifier,
 ) {
     val lottieComposition by rememberLottieComposition(RawRes(raw.add_to_bookmark_lottie))
-    val animationRange = 0.1f..1f
     var isPlaying by remember { mutableStateOf(false) }
 
-    val progress by animateLottieCompositionAsState(
+    val state = animateLottieCompositionAsState(
```
Comment (takahirom) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt:35]: What if we name this `lottieCompositionState`?

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/TimetableScreen.kt (hunk 4 above)
Comment (ked4ma) [reply feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/TimetableScreen.kt]: I add parameter names to this preview :smiley: 
(https://github.com/DroidKaigi/conference-app-2023/pull/1131/commits/66f1cce05a15f6a39a2049ca2096fec77048a286)

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt (hunk 5 above)
Comment (ked4ma) [reply feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/BookmarkIcon.kt]: it's more understandable.
i changed it from `state` to `lottieState`
(https://github.com/DroidKaigi/conference-app-2023/pull/1131/commits/5e7f7cf99450149105ee10aadd5a4773fce37cb1)

**Review by takahirom — APPROVED** [review]
Looks great! Thanks for the consistent screen!
