### PR TITLE
Fix NestedScroll Issue in Timetable Grid to Allow Tab Shrinking on Scroll

### LINKED ISSUE #498: Fix NestedScroll Issue in Timetable Grid to Allow Tab Shrinking on Scroll
In the Timetable grid section of the DroidKaigi app, the NestedScroll functionality is not working as expected. As a result, tabs and other elements do not shrink in response to scrolling. This affects the user experience and needs to be addressed.

### Expected Behavior
Tabs should shrink when the user scrolls through the timetable grid.

### Current Behavior
Tabs remain fixed and do not respond to scrolling.

### PR DESCRIPTION
**Pull request by usuiat**
This pull request partially resolves Issue #498 .
Dragging TimetableGrid can shrink or expand the header and the tab.
However, fling is not yet supported. Therefore, the size of the header and the tab will not change after the gesture ends.
Resolving it may take more time, so I submit this pull request for supporting only drag.

## Issue
- close #498 

## Overview (Required)
- Shrink header and tab when TimetableGrid is dragged.

## Links
- 

## Screenshot

Before | After
:--: | :--:
 <video src="https://github.com/DroidKaigi/conference-app-2023/assets/17829294/470ae554-2e30-43f5-bdad-8d7689ea6ef4" width="300" /> | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/17829294/abff572f-3f42-44a4-9241-fbba6f10f3ed" width="300" />

### CODE REVIEW

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableGrid.kt [hunk 1]
```diff
@@ -572,15 +579,29 @@ private class TimetableScreen(
...
+        val parentConsumed = nestedScrollDispatcher.dispatchPreScroll(
+            available = dragAmount,
+            source = NestedScrollSource.Drag,
+        )
+        val nextPossibleX = calculatePossibleScrollX(dragAmount.x - parentConsumed.x)
+        val nextPossibleY = calculatePossibleScrollY(dragAmount.y - parentConsumed.y)
+        val weConsumed = Offset(
+            nextPossibleX - scrollState.scrollX,
+            nextPossibleY - scrollState.scrollY,
+        )
```
Comment (NUmeroAndDev) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableGrid.kt:593]: 👍

**Review by NUmeroAndDev — APPROVED** [review]
Looks great! 
Thanks for your contribution!
