### PR TITLE
modify session grid speaker text to fix bottom

### LINKED ISSUE #731: Fix the speaker to the bottom.
**Idea Description**
Currently, the session grid items are rendered as shown in the image below.
We would like the speaker to be fixed on the bottom to match the Figma design.

**Reference images and links**
Figma | Actual
 :-: | :-:
 |

### PR DESCRIPTION
**Pull request by Aniokrait**
## Issue
- close #731

## Overview (Required)
- fix the problem that a session speaker text was not fixed to bottom like in Figma.

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableGridItem.kt [hunk 1]
```diff
@@ -123,7 +124,11 @@ fun TimetableGridItem(
                 )
             }
 
-            Spacer(modifier = Modifier.height(TimetableGridItemSizes.scheduleToSpeakerSpaceHeight))
+            Spacer(
+                modifier = Modifier
+                    .weight(1f)
```
Comment (takahirom) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableGridItem.kt:129]: 👍

**Review by takahirom — APPROVED** [review]
Looks great! Thank you for your simple implementation!
