### PR TITLE
Hide searching text when enable the BigFont/BigDisplay

### LINKED ISSUE #790: Hide searching text  when enable the BigFont/BigDisplay
**Describe the bug**
Hide searching text  when enable the BigFont/BigDisplay

Applicable part
https://github.com/DroidKaigi/conference-app-2023/blob/66551e42d017d843da50ec9da26058d05cf002b4/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/SearchTextFieldAppBar.kt#L42

**To Reproduce**
1. enable the BigFont/BigDisplay
2. Go to Serach Screen

**Related Issues**
- #720 
- #464 

**Expected behavior**
Enabling BigFont/BigDisplay does not cause character broken

**Screenshots**
Phone: Pixel6
|Settings|Search Screen|
|---|---|
|||

### PR DESCRIPTION
**Pull request by shinya-tan**
## Issue
- close #790 

## Overview (Required)
- Implementing it so that the searching text doesn't distort when increasing the font size. 

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
BigFont/BigDisplay setting |
:--: |
 |

### NormalFont
Before | After
:--: | :--:
 | 

### BigFont
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
<video src="" width="300" > | <video src="" width="300" >

### CODE REVIEW

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/SearchTextFieldAppBar.kt [hunk 1]
```diff
@@ -92,7 +91,6 @@ private fun SearchTextField(
         value = searchQuery,
         onValueChange = onSearchQueryChanged,
         modifier = modifier
-            .height(56.0.dp)
```
Comment (shinya-tan) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/SearchTextFieldAppBar.kt:95]: Due to the set height of the BasicTextField, the text was getting cut off.

**Comment by takahirom** [comment]
Could you add a screenshot test like this? 🙏 
https://github.com/DroidKaigi/conference-app-2023/pull/970#issuecomment-1694245405

**Comment by shinya-tan** [comment]
OK. I'll handle it.

**Comment by shinya-tan** [comment]
@takahirom 
I have a question.
Regarding the screenshot tests, will you add them for fonts other than large?

**Comment by takahirom** [comment]
I'll leave it to you! If you think it is convenient, you can add it!

File: feature/sessions/src/test/java/io/github/droidkaigi/confsched2023/sessions/SearchScreenTest.kt [hunk 2]
```diff
@@ -43,6 +43,36 @@ class SearchScreenTest {
         }
     }
 
+    @Test
+    @Category(ScreenshotTests::class)
+    @Config(fontScale = 0.5f)
+    fun smallFontScaleShot() {
```
Comment (takahirom) [inline feature/sessions/src/test/java/io/github/droidkaigi/confsched2023/sessions/SearchScreenTest.kt:49]: We are using check○○Shot() as naming🙏

Comment (shinya-tan) [reply feature/sessions/src/test/java/io/github/droidkaigi/confsched2023/sessions/SearchScreenTest.kt:49]: Sure! I'll handle it.

Comment (shinya-tan) [reply feature/sessions/src/test/java/io/github/droidkaigi/confsched2023/sessions/SearchScreenTest.kt]: https://github.com/DroidKaigi/conference-app-2023/pull/972/commits/be43cf32eb2093bdc55805dbc6c5d6c8c670683d
I have addressed it

**Review by takahirom — APPROVED** [review]
Thanks! Looks better!
