### PR TITLE
Customize Chip Colors According to Room Labels 

### LINKED ISSUE #501: Customize Chip Colors According to Room Labels
**Idea Description**

In the DroidKaigi app, we have the opportunity to enhance the visual differentiation of room labels by changing the color of the corresponding Chips.

### Expected Behavior
Chips should have distinct colors based on the room labels they represent.

### Current Behavior
All Chips have the same color, regardless of room label.

### Steps to Reproduce
Provide steps on how to reproduce this issue...

### Additional Information
Provide any additional information or screenshots...

**Reference images and links**
https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI
image

### PR DESCRIPTION
**Pull request by kosenda**
## Issue
- close #501 

## Overview (Required)
- The reason why the color did not change was that the sortIndex was always set to 0
- Used `associateBy` to make it clear that it is a `Map<Int, TimetableRoom>`

## Log
I used `.also { println(it) }` at the end of the variable `roomIdToRoom` that I changed this time to output the log
- Before
```
{35497=TimetableRoom(id=35497, name=MultiLangText(jaTitle=Chipmunk, enTitle=Chipmunk), sort=0, sortIndex=0), 37290=TimetableRoom(id=37290, name=MultiLangText(jaTitle=Dolphin, enTitle=Dolphin), sort=4, sortIndex=0), 37291=TimetableRoom(id=37291, name=MultiLangText(jaTitle=Electric Eel, enTitle=Electric Eel), sort=5, sortIndex=0), 35499=TimetableRoom(id=35499, name=MultiLangText(jaTitle=Bumblebee, enTitle=Bumblebee), sort=2, sortIndex=0), 35498=TimetableRoom(id=35498, name=MultiLangText(jaTitle=Arctic Fox, enTitle=Arctic Fox), sort=1, sortIndex=0)}
```
- After
```
{35497=TimetableRoom(id=35497, name=MultiLangText(jaTitle=Chipmunk, enTitle=Chipmunk), sort=0, sortIndex=0), 37290=TimetableRoom(id=37290, name=MultiLangText(jaTitle=Dolphin, enTitle=Dolphin), sort=4, sortIndex=3), 37291=TimetableRoom(id=37291, name=MultiLangText(jaTitle=Electric Eel, enTitle=Electric Eel), sort=5, sortIndex=4), 35499=TimetableRoom(id=35499, name=MultiLangText(jaTitle=Bumblebee, enTitle=Bumblebee), sort=2, sortIndex=2), 35498=TimetableRoom(id=35498, name=MultiLangText(jaTitle=Arctic Fox, enTitle=Arctic Fox), sort=1, sortIndex=1)}
```

## Links
- [Kotlin - associateBy](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/associate-by.html)

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

File: core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/data/sessions/DefaultSessionsApiClient.kt [hunk 1]
```diff
@@ -70,19 +70,19 @@ internal fun SessionsAllResponse.toTimetable(): Timetable {
                 )
             }.first()
         }
-    val roomIdToRoom = timetableContents.rooms
-        .groupBy { it.id }
-        .mapValues { (_, apiRooms) ->
-            apiRooms.map { apiRoom ->
-                val roomSorts = apiRooms.map { it.sort }.sorted()
+    val roomIdToRoom: Map<Int, TimetableRoom> = timetableContents.rooms
+        .associateBy(
```
Comment (takahirom) [inline core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/data/sessions/DefaultSessionsApiClient.kt:74]: 👍

**Review by takahirom — APPROVED** [review]
Thanks for fixing and elegant code!
