### PR TITLE
Fix time text format

### LINKED ISSUE #834: Color of text is wrong in timetable screen
**Idea Description**
The session end time should have different color

**Reference images and links**

スクリーンショット 2023-08-21 22 03 04

### PR DESCRIPTION
**Pull request by CookieySun**
## Issue
- close #834

## Overview (Required)
- Add color and font weight to timetable.

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
<video src="" width="300" > | <video src="" width="300" >

### CODE REVIEW

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableList.kt [hunk 1]
```diff
@@ -94,9 +96,13 @@ fun TimetableList(
                             text = timetableItem.startsTimeString,
                             fontWeight = FontWeight.Medium,
                         )
-                        Text(text = "|")
+                        Text(text = "|",
+                            color = md_theme_light_outlineVariant,
+                        )
                         Text(
                             text = timetableItem.endsTimeString,
+                            color = md_theme_light_secondary,
```
Comment (takahirom) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableList.kt:104]: I think we should use a Theme color for this because it will break when you use dark theme 👀

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableList.kt [hunk 2]
```diff
@@ -94,9 +96,13 @@ fun TimetableList(
                             text = timetableItem.startsTimeString,
                             fontWeight = FontWeight.Medium,
                         )
-                        Text(text = "|")
+                        Text(text = "|",
+                            color = md_theme_light_outlineVariant,
+                        )
```
Comment (takahirom) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableList.kt:101]: Could you put this back?  This is because there is a different PR that will cause conflict 🙏

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableList.kt (hunk 1 above)
Comment (CookieySun) [reply feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/section/TimetableList.kt]: I fix it!

**Review by takahirom — APPROVED** [review]
Looks better! Thanks!
