### PR TITLE
Fixed contributors screen crash on communication error

### LINKED ISSUE #752: Crash when open contributors screen offline
**Describe the bug**
App will crash when you open contributors screen **offline**

**To Reproduce**
1. modify `DefaultRemoteConfigApi.getBoolean(...)` due to crashing by other issue (#734)
    ```kotlin
    actual override suspend fun getBoolean(key: String): Boolean {
     + try {
            firebaseRemoteConfig.fetchAndActivate()
     + } catch (exception: FirebaseException) {
     +     Log.e("DefaultRemoteConfig", exception.message, exception)
     + }
        return firebaseRemoteConfig[key]
    }
    ```
2. set device **offline**
3. launch app
4. go to contributors from bottom nav bar
5. crash app

**Expected behavior**
- Not crash.
- (show snackbar or some info to user)

**Screenshots**

https://github.com/DroidKaigi/conference-app-2023/assets/74723074/44e2bd5b-611b-48b2-8867-1f3c9109660b

### PR DESCRIPTION
**Pull request by hoashi-akane**
## Issue
- close #752

## Overview (Required)
- When a communication error occurs on the Contributors screen
Show the snackbar.
- UUID.mostSignificantBits was used for the UserMessage.id, but since there is no similar function in IOS, the UUID hash code is used as the id.

## Movie (Optional)
Before | After
:--: | :--:
<video src="https://github.com/DroidKaigi/conference-app-2023/assets/51166726/b94bbaa1-9255-46c1-b269-acb029d02bbe" width="300" > | <video src="https://github.com/DroidKaigi/conference-app-2023/assets/51166726/f7039093-0015-4f59-aca5-bab601e19ed5" width="300" >

### CODE REVIEW

File: feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/contributors/ContributorsViewModel.kt [hunk 1]
```diff
@@ -13,10 +16,15 @@ import kotlinx.coroutines.flow.stateIn
...
 class ContributorsViewModel @Inject constructor(
-    contributorsRepository: ContributorsRepository
-) : KmpViewModel() {
+    contributorsRepository: ContributorsRepository,
+    val userMessageStateHolder: UserMessageStateHolder,
+) : KmpViewModel(), UserMessageStateHolder by userMessageStateHolder {
     private val contributors = contributorsRepository
         .contributors()
+        .handleErrorAndRetry(
+            AppStrings.Retry,
```
Comment (fumiya-kume) [inline feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/contributors/ContributorsViewModel.kt:25]: [nit] Sorry for sudden comments 🙇 As a beginner of codebase, It's nice to have a arguments name for the method calling. & this comments should not be blocker for the PR merging. 
Just a randomly comments 🙇

Comment (takahirom) [reply feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/contributors/ContributorsViewModel.kt:25]: You have a point. But maybe the rest of the code for handleErrorAndRetry doesn't use named arguments. Maybe we can work on another issue.

File: core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/ui/UserMessage.kt [hunk 2]
```diff
@@ -124,3 +124,20 @@ enum class UserMessageResult {
     Dismissed,
     ActionPerformed,
 }
+
+class FakeUserMessageStateHolder : UserMessageStateHolder {
```
Comment (takahirom) [inline core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/ui/UserMessage.kt:128]: May I ask why you need this for iOS? 👀
